services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack_s3
    ports:
      - '4566:4566'
      - '4572:4572'
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/var/lib/localstack/data
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - './localstack-data:/var/lib/localstack/data'
      - './.localstack:/var/lib/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
  redis:
    image: redis:7.2-alpine
    container_name: redis_bullmq
    ports:
      - '6379:6379'
    volumes:
      - './redis-data:/data'
